### ISSUE TITLE
Weird data in Arduino

### ISSUE THREAD

**Issue by gepd** [BLavery/lib_nrf24#2]
Hi, after try with many libraries, this one works just fine in my Raspberry pi, well almost all.

I sent a text from the Arduino to the RPi and all work fine, I received the ACSII text

But when I try to send from RPi to the Arduino, with `writeAckPayload()` or `write()` I didn't receive the ACSII text

I send `buf = ['1']` (from RPi)

And in Arduino: 

```
char msg[32]; 
radio.read( &msg, sizeof(msg) );
printf("receiving: %c\n",msg);
```

But the output is `825297112`

what kind of data is it?
what I'm doing wrong?

**Comment by Gabedu2000** [comment]
Hi! You could solved this problem? Thanks
